DROP DATABASE IF EXISTS Usuario;
CREATE DATABASE Usuario;
USE Usuario;


CREATE TABLE usuario(
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
nick VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL
);



SELECT * FROM usuario;